#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom aws.s3 s3readRDS
#' @importFrom aws.s3 s3saveRDS
#' @importFrom bslib card_body
#' @importFrom checkmate assert
#' @importFrom checkmate assert_character
#' @importFrom checkmate assert_class
#' @importFrom checkmate assert_data_frame
#' @importFrom checkmate assert_integerish
#' @importFrom checkmate assert_list
#' @importFrom checkmate assert_names
#' @importFrom checkmate assert_numeric
#' @importFrom checkmate assert_string
#' @importFrom checkmate assert_vector
#' @importFrom checkmate check_environment
#' @importFrom checkmate check_logical
#' @importFrom data.table :=
#' @importFrom data.table as.data.table
#' @importFrom data.table copy
#' @importFrom data.table rbindlist
#' @importFrom DBI dbClearResult
#' @importFrom DBI dbConnect
#' @importFrom DBI dbDisconnect
#' @importFrom DBI dbFetch
#' @importFrom DBI dbGetQuery
#' @importFrom DBI dbSendQuery
#' @importFrom DT datatable
#' @importFrom DT dataTableOutput
#' @importFrom DT formatStyle
#' @importFrom DT renderDataTable
#' @importFrom glue glue
#' @importFrom glue glue_collapse
#' @importFrom htmlwidgets JS
#' @importFrom htmlwidgets onRender
#' @importFrom httr2 req_error
#' @importFrom httr2 req_headers
#' @importFrom httr2 req_perform
#' @importFrom httr2 resp_body_json
#' @importFrom httr2 resp_body_string
#' @importFrom httr2 resp_status
#' @importFrom jsonlite toJSON
#' @importFrom leaflet leafletOutput
#' @importFrom leaflet renderLeaflet
#' @importFrom magrittr %>%
#' @importFrom magrittr %T>%
#' @importFrom magrittr divide_by
#' @importFrom plotly add_trace
#' @importFrom plotly plot_ly
#' @importFrom plotly plotlyOutput
#' @importFrom plotly renderPlotly
#' @importFrom R6 R6Class
#' @importFrom RMariaDB MariaDB
#' @importFrom sf st_as_sf
#' @importFrom sf st_drop_geometry
#' @importFrom sf st_geometry
#' @importFrom shinycssloaders withSpinner
#' @importFrom shinyWidgets dropdownButton
#' @importFrom stats setNames
#' @importFrom utils capture.output
#' @importFrom utils write.csv
## usethis namespace: end
NULL
